module;
export module type_enums;
export import :unit_enum;
export import :ability_enums;
export import :upgrade_enum;
export import :buff_enum;
export import :effect_enum;

/*! @brief A list of enums provided for your convenience.
 *
 * All units and abilities are represented as unsigned numbers in the StarCraft
 * II engine. This file aims to provide a type safe and named way of
 * representing various game types. Entries in it are generated by a custom
 * utility located at https://github.com/cpp-sc2/codegen
 */

